package General;

public class Support {

    private static int num_nodes_generated;

    /**
     * @Brief Increases the number of nodes generated by n
     */
    public static void increaseNodesGenerated(int n)
    {
        num_nodes_generated+=n;
    }

    /**
     * @Brief Gets the number of nodes generated
     */
    public static int getNumNodesGenerated()
    {
        return num_nodes_generated;
    }

    /**
     * @Brief sets num nodes generated to 0
     */
    public static void resetNumNodesGenerated()
    {
        num_nodes_generated = 0;
    }

}
